# EXEMPLES ALGEBRA

Anem a veure com fer vectors i matrius, per això activem el Numpy:

In [2]:
import numpy as np

 # Exemple de vectors (array)

In [3]:
v=np.array([1,0,0]) 
u=np.array([0,-2,0])
#np.array() ens permet escriure els vectors u y v

In [4]:
print(u)

[ 0 -2  0]


3. Operacions amb vectors (suma, resta, producte escalar y prod. vectorial)

In [5]:
w1=u+v
print(w1)
w2=u-v
print(w2)

[ 1 -2  0]
[-1 -2  0]


In [6]:
#Producte escalar
a=np.dot(u,v)
print(a)

0


In [8]:
#Producte vectorial
b=np.cross(v,u)
print(b)

[ 0  0 -2]


# EXEMPLES DE MATRIUS

In [15]:
A=np.array([[2,4],[1,3]])
print(A)

[[2 4]
 [1 3]]


In [18]:
e=A[1,0] # Agafa l'element de la fila 1 i la columna 0 de la matriu
print(e)

1


In [19]:
# Seleccionar una fila o columna sencera a partir d'un vector
v=A[0,:] # ES defineix un vector v que es basa en tota la primera fila (0) i tots els elements, totes les coulmnes d'aquesta fila (:)
print(v)

[2 4]


In [21]:
u=A[:,1] # Amb això estem agafant tota la primera columna.
print(u)

[4 3]


Anem a diagonalitzar matrius i per això necessitem obtenir els valors pròpis, els vectors pròpis...:

1. Vectors pròpis:

In [46]:
A=np.array([[2,2],[1,3]])
print(A)

[[2 2]
 [1 3]]


In [47]:
# Valors de vectors pròpis (si no es sap quina és la comanda necessària, es busca a la pàgina web de Numpy)
Valors,Vectors = np.linalg.eig(A) #Ambs això es calcula els valors i vectors pròpis
print("Valors propis",Valors)
print("Vectors propis",Vectors)

Valors propis [1. 4.]
Vectors propis [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [48]:
u=Vectors[:,0] #Amb això estrec el primer vector pròpi que està a la primera columna
print(u)

[-0.89442719  0.4472136 ]


In [49]:
v=Vectors[:,1]
print(v)
# Amb això estrec el segon vector pròpi

[-0.70710678 -0.70710678]


In [50]:
z=np.dot(A,u) #Multplicar la matriu A per el vector u. Amb això comprobem que efectivament son vectors pròpis.
print(z)

[-0.89442719  0.4472136 ]


In [51]:
z2=np.dot(A,v) #Multplicar la matriu A per el vector v. Amb això comprobem que efectivament son vectors pròpis.
print(z2)

[-2.82842712 -2.82842712]


ALTRES EXEMPLES DE MATRIUS:

In [53]:
#Crear una matriu que sigui 0 tota l'estona
A=np.zeros([3,3]) #Creem una mariu 3x3 que sigui TOTA de zeros
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
